# Generated by Django 3.2.9 on 2021-11-26 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='DireccionBienes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cedula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Direccion de Bienes',
                'verbose_name_plural': 'Direccion de Bienes',
            },
        ),
        migrations.CreateModel(
            name='ResponsablePatrimonio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cedula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Responsable del Patrimonio',
                'verbose_name_plural': 'Responsable del Patrimonio',
            },
        ),
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cedula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento', verbose_name='Jef@ del Departamento')),
            ],
            options={
                'verbose_name': 'Jefe del Departamento',
                'verbose_name_plural': 'Jefe del Departamento',
            },
        ),
        migrations.CreateModel(
            name='InventarioAdministracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Administracion',
                'verbose_name_plural': 'Inventario Administracion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalResponsablePatrimonio',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cedula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Responsable del Patrimonio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJefeDepartamento',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cedula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.departamento', verbose_name='Jef@ del Departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Jefe del Departamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDireccionBienes',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=15, verbose_name='Cedula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Direccion de Bienes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDepartamento',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Departamento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
