# Generated by Django 3.2.9 on 2021-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioVivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Vivienda',
                'verbose_name_plural': 'Inventario Vivienda',
            },
        ),
        migrations.CreateModel(
            name='InventarioSunavi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Sunavi',
                'verbose_name_plural': 'Inventario Sunavi',
            },
        ),
        migrations.CreateModel(
            name='InventarioSistemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Sistemas',
                'verbose_name_plural': 'Inventario Sistemas',
            },
        ),
        migrations.CreateModel(
            name='InventarioSaren',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Saren',
                'verbose_name_plural': 'Inventario Saren',
            },
        ),
        migrations.CreateModel(
            name='InventarioSalaSituacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Sala Situacional',
                'verbose_name_plural': 'Inventario Sala Situacional',
            },
        ),
        migrations.CreateModel(
            name='InventarioRedesPopulares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Redes Populares',
                'verbose_name_plural': 'Inventario Redes Populares',
            },
        ),
        migrations.CreateModel(
            name='InventarioObras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Obras',
                'verbose_name_plural': 'Inventario Obras',
            },
        ),
        migrations.CreateModel(
            name='InventarioJubilados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Jubilados',
                'verbose_name_plural': 'Inventario Jubilados',
            },
        ),
        migrations.CreateModel(
            name='InventarioIntu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Intu',
                'verbose_name_plural': 'Inventario Intu',
            },
        ),
        migrations.CreateModel(
            name='InventarioInmobiliariaNacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Inmobiliaria Nacional',
                'verbose_name_plural': 'Inventario Inmobiliaria Nacional',
            },
        ),
        migrations.CreateModel(
            name='InventarioGestionHumana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Gestion Humana',
                'verbose_name_plural': 'Inventario Gestion Humana',
            },
        ),
        migrations.CreateModel(
            name='InventarioDireccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Direccion',
                'verbose_name_plural': 'Inventario Direccion',
            },
        ),
        migrations.CreateModel(
            name='InventarioBarrioNuevoTricolor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Barrio Nuevo Barrio Tricolor',
                'verbose_name_plural': 'Inventario Barrio Nuevo Barrio Tricolor',
            },
        ),
        migrations.CreateModel(
            name='InventarioBanhaviFao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Banhavi Fao',
                'verbose_name_plural': 'Inventario Banhavi Fao',
            },
        ),
        migrations.CreateModel(
            name='InventarioBanhaviCobranza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Banhavi Cobranza',
                'verbose_name_plural': 'Inventario Banhavi Cobranza',
            },
        ),
        migrations.CreateModel(
            name='InventarioAtencionCiudadano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Atencion Ciudadano',
                'verbose_name_plural': 'Inventario Atencion Ciudadano',
            },
        ),
        migrations.CreateModel(
            name='InventarioAsesoriaLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDelBien', models.CharField(max_length=50, unique=True, verbose_name='N° Provisional del Bien')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('caracteristica', models.CharField(max_length=50, verbose_name='Caracteristicas')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de Conservacion')),
                ('observacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observacion')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Inventario Asesoria Legal',
                'verbose_name_plural': 'Inventario Asesoria Legal',
            },
        ),
    ]
