# Generated by Django 3.2.9 on 2021-12-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211202_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioadministracion',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventarioadministracion',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventarioasesorialegal',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventarioasesorialegal',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventarioatencionciudadano',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventarioatencionciudadano',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariobanhavicobranza',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariobanhavicobranza',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariobanhavifao',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariobanhavifao',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariobarrionuevotricolor',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariobarrionuevotricolor',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariodireccion',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariodireccion',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariogestionhumana',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariogestionhumana',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventarioinmobiliarianacional',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventarioinmobiliarianacional',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariointu',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariointu',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariojubilados',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariojubilados',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventarioobras',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventarioobras',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventarioredespopulares',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventarioredespopulares',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariosalasituacional',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariosalasituacional',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariosaren',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariosaren',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariosistemas',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariosistemas',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariosunavi',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariosunavi',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
        migrations.RemoveField(
            model_name='inventariovivienda',
            name='departamento',
        ),
        migrations.AddField(
            model_name='inventariovivienda',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento', verbose_name='Departamento'),
        ),
    ]
